# Generated by Django 4.1.13 on 2024-05-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='views',
            field=models.IntegerField(null=True),
        ),
    ]
